apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.name }}

type: {{ .Values.secret.type }}

data:
  DB_User: {{ .Values.secret.data.DB_User }}
  DB_Pass: {{ .Values.secret.data.DB_Pass }}